- name: Configure Nginx proxy locations for users
  template:
    src: "{{ playbook_dir }}/templates/user_proxy_locations.conf.j2"
    dest: /etc/nginx/conf.d/user_proxy_locations.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx