- name: Install python3-venv  #move to droplet creation
  apt:
    name: python3-venv
    state: present
    update_cache: yes
  check_mode: yes
  register: pip_check
  
- name: Actually install python3-venv
  apt:
    name: python3-venv
    state: present
  when: pip_check.changed

- name: Check python3-pytest installation
  apt:
    name: 
      - python3-pytest
      - python3-pytest-cov
      - python3-coverage
    state: present
  check_mode: yes
  register: pytest_check
  tags: install_pytest

- name: Install python3-pytest
  apt:
    name:
      - python3-pytest
      - python3-pytest-cov
      - python3-coverage
    state: present
    update_cache: yes
  when: pytest_check.changed
  tags: install_pytest

- name: Check python3-venv installation
  apt:
    name: python3-venv
    state: present
  check_mode: yes
  register: pip_check

- name: Install python3-venv
  apt:
    name: python3-venv
    state: present
  when: pip_check.changed

- name: Check python3-pip installation
  apt:
    name: python3-pip
    state: present
  check_mode: yes
  register: pip_check

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present
  when: pip_check.changed