- name: Check nginx installation
  command: dpkg -l nginx
  register: nginx_check
  changed_when: false
  failed_when: false

- name: Wait for automatic system updates to complete
  shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done
  timeout: 300

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  register: nginx_install
  until: nginx_install is succeeded
  retries: 5
  delay: 30
  when: nginx_check.rc != 0

- name: Create Nginx conf.d directory
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: '0755'
    owner: root
    group: root